# .github/workflows/codecov.yml

name: Codecov

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
